create table MQTT_MQTT_MSG (
    ID bigint generated by default as identity(start with 1) not null,
    UUID varchar(36),
    CREATE_TS timestamp,
    CREATED_BY varchar(50),
    --
    MSG longvarchar
);